language: node_js

node_js:
  - "0.10"
before_install:
  - sudo apt-get install autoconf automake libtool
  - sudo apt-get install libpng12-dev
  - sudo apt-get install libjpeg62-dev
  - sudo apt-get install libtiff4-dev
  - sudo apt-get install zlib1g-dev
install:
  - npm install
script:
  - npm test
